import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './local.css'
import './radar.css'
import './responsive.css'
import './creative-platform.css'
import './guide.css'
import './simplify-flow.css'
import './shoot-pack.css'
import './qv-logo.css'
import './inspiration.css'
import './reference-mode.css'
import './autocut.css'
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
if ('serviceWorker' in navigator) navigator.serviceWorker.getRegistrations().then(registrations => registrations.forEach(registration => registration.unregister()))
